package com.ftn.security.model;

public enum ExtendedKeyUsage {
    TSL_WEB_SERVER_AUTHENTICATION,
    TLS_WEB_CLIENT_AUTHENTICATION,
    SIGN_EXECUTABLE_CODE,
    EMAIL_PROTECTION,
    IPSEC_END_SYSTEM,
    IPSEC_TUNNEL,
    IPSEC_USER,
    TIMESTAMPING
}
